<?php
	require_once('../assets/php/config.php');

	$pageName = $mpArticle->data['article_page_name'];

?>
<!DOCTYPE html>
<html class="no-js" lang="en">
<?php include_once($config['include_path'].'head.php');?>
<body id="policy">
	<?php if($detect->isMobile()){
		include_once($config['include_path'].'header.php'); 
	}else{
		include_once($config['include_path'].'new_header.php'); 
	}?>
<?php include_once($config['include_path'].'header_ad.php'); ?>

<main id="main" class="row panel sidebar-on-right" role="main">
		<section id="puc-articles" class="sidebar-right shadow-on-large-up mobile-12 small-12 medium-12 large-11 columns translate-fix sidebar-main-left">
<section class="small-12 columns sidebar-right">
<h2>Terms of Service</h2>
<p class="bold">Effective as of: January 1, 2015</p>
<p>USERS UNDER THE AGE OF 18 ARE NOT ALLOWED TO REGISTER TO ACCEPT PAYMENTS WITHOUT THE WRITTEN APPROVAL OF THE USERS’ PARENT OR LEGAL GUARDIAN. BY SIGNING UP FOR THIS SERVICE, YOU HEREBY ACKNOWLEDGE THAT YOU ARE AGE 18 OR OVER.
</p>
<p>THESE TERMS OF SERVICE PROVIDES THAT ALL DISPUTES WILL BE RESOLVED BY BINDING ARBITRATION AND NOT IN COURT OR BY JURY TRIAL. YOU ALSO AGREE TO RELINQUISH YOUR RIGHT TO PARTICIPATE AS A CLASS REPRESENTATIVE OR CLASS MEMBER ON ANY CLASS ACTION CLAIM YOU MAY HAVE AGAINST SEQUEL MEDIA INTERNATIONAL, LLC.
</p>
<p>By agreeing to the Terms of Service and <a href="http://www.puckermob.com/privacy/">Privacy Policy</a> when signing up for an account with PuckerMob.com (a site wholly owned by Sequel Media International, LLC), or by using this Site, you have agreed to These Terms of Service and the Sequel Media International, LLC <a href="http://www.puckermob.com/privacy/">Privacy Policy</a> hereby incorporated by reference, which details the ways in which we use personal information that belongs to or is related to you.
</p>
<p>These Terms of Service ("Terms") are between you and Sequel Media International, LLC (“Sequel Media International, LLC”, “we”, “us” or “our”) with regard to the PuckerMob.com website (defined below) (the “Site”). Please read them carefully. In addition, if you are registering to use services on the Site or accessed via the Site, you agree to be subject to any rules or guidelines applicable to such services, and such rules or guidelines will be incorporated by reference within these Terms of Service. If you do not agree to these Terms of Service, or you do not meet any eligibility requirements established by Sequel Media International, LLC for use of and access to the Site, you may not access, view, obtain services from, or otherwise use the Site.
</p>
<p>You agree to the terms and conditions of Sequel Media International, LLC <a href="http://www.puckermob.com/privacy/">Privacy Policy</a> (“PRIVACY POLICY”) hereby incorporated by reference, which details the ways in which we use personal information that belongs to or is related to you.
</p>

<h3>"SITE" DEFINED</h3>
<p>The “Site” encompasses PuckerMob.com and any and all subdomains or affiliated landing pages, sites and mini-sites, and all associated web pages, including without limitation all content, materials, information, policies, modifications, updates, enhancements, revisions, new features, and or new web properties of such pages, along with all Site services provided through such websites and web pages. The purpose of the Site is to (a) provide users of the publicly accessible portion of the Site with access to certain content concerning PuckerMob.com, its products and services, and related information as a complementary service for entertainment, informational and educational purposes only, and (b) provide certain tools such as player pages to users of the password-protected portion of the Site (collectively, “Purpose”).
</p>

<h3>MODIFICATION OF THESE TERMS OF SERVICE AND THE SITE</h3>
<p>You are responsible for regularly reviewing these Terms of Service. Sequel Media International, LLC has the right, but not the obligation, to correct any errors or omissions in any portion of the Site and these Terms of Service. Sequel Media International, LLC reserves the right, in its sole discretion, to change, modify, add, remove or terminate any portion of the Site or these Terms of Service, in whole or in part, at any time, without prior notice. All changes to these Terms of Service are effective immediately upon being posted to the Site. Your continued use of the Site following any changes to these Terms of Service will mean you accept these changes.
</p>

<h3>SITE USE</h3>
<p>The following points regarding compensation apply to “Bloggers” only. “Freelance” writers maybe be compensated differently, and that compensation rate will be established separately. All other portions of this Terms of Service apply to all writers.</p>
<p>Compensation Policy for Revenue Program</p>
<p>You may receive a portion of revenue (“Revenue Program”) by Sequel Media International, LLC in connection with authenticate genuine social interactions (“likes,” shares, comments, and views) on the Site by posting valid content. If you violate this Compensation Policy, Sequel Media International, LLC Terms of Service or <a href="http://www.puckermob.com/privacy/">Privacy Policy</a>, we may, in our sole discretion, without notice, reduce or eliminate your compensation, terminate this Agreement, delete your content, and/or suspend or terminate your user account.</p>
<p>By registering on our Site and posting content or interacting with Site content, you hereby represent, acknowledge, agree, and warrant that:</p>

<ol>
<li>You agree to abide by the Sequel Media International, LLC Terms of Service and <a href="http://www.puckermob.com/privacy/">Privacy Policy</a>.</li>
<li>Sequel Media International, LLC is constantly changing and improving the Site and Revenue Program. We may add or remove functionalities, features or methods of calculations of the Revenue Program at any time, and we may suspend or stop the Revenue Program altogether.
<li>We may modify the Compensation Policy, Terms of Service or <a href="http://www.puckermob.com/privacy/">Privacy Policy</a> at any time and without notice. Any material modification to the Compensation Policy, Terms of Service or <a href="http://www.puckermob.com/privacy/">Privacy Policy</a> will be posted on their respective pages. Material modifications will not apply retroactively and generally will become effective 14 days after they are posted. What constitutes “material” will be determined by Sequel Media International, LLC in its sole discretion. Changes addressing new functionality in the Revenue Program or changes made for legal reasons will be effective immediately. If you don’t agree to such modifications, you must stop participating in the Revenue Program.</li>
<li>Posts must contain valid content to be eligible for the Revenue Program as follows:
<ul>
	<li>An eligible post must contain original text of at least 1,000 characters, be authored by you, and be written in the English language or include an English translation;</li>
	<li>An eligible post containing an image must be accompanied by text of at least 1,000 characters and be your originally created image, or be suitably licensed to you, or uses images from any Sequel Media International, LLC’ photo and image library that may be provided;</li>
	<li>An eligible post will not contain unsuitable content, including but not limited to, plagiarized or infringing text or images, falsified or misattributed content, obscene, pornographic, pseudo-pornographic, defamatory, bigoted or invasive content, will not incite others to commit violence, will not contain previously published materials, whether public domain or your previously published content, unless additional text of at least 1,000 characters is included in such post, will not contain the intellectual property of Sequel Media International, LLC or third parties, and will not violate the Site Restrictions section of the Terms of Service ; and</li>
	<li>An eligible post will not contain content, falsified user information, referral or affiliate links to other Sites, or directly or indirectly generate likes, comments, or views of posts.</li>
</ul>
</li>
<li>Social interactions with eligible posts must be authentic to be eligible for redemption of compensation under Revenue Program. Therefore you will not:
	<ul>
		<li>Abuse the Site’s likes/views/comment system by any means including but not limited to use of exchange groups, or utilizing code, tags, cookies, Traffic Exchange, bots, proxies, virtual private networks, or other forms of social or digital manipulation to generate non-authentic likes/views/comment on your posts; or</li>
		<li>Use any automated, deceptive, fraudulent or other invalid means (including, but not limited to, click spam, robots, macro programs, and Internet agents) to encourage or require other users or any other persons, either with or without their knowledge, to like/view/comment on posts, by offering incentives or any other methods that are manipulative, deceptive, malicious or fraudulent.</li>
	</ul>
</li>
<li>Earnings (if any) from eligible posts and social interactions shall not be redeemed until your Revenue Program account exceeds $50.00; however your compensation may be forfeited and your account terminated if such revenue was produced by ineligible posts and/or non-authentic social interactions (likes/views/comments).</li>
<li>You are not an employee, partner, or agent of Sequel Media International, LLC and shall be solely responsible for any and all applicable taxes, excise, value added or other applicable taxes, tariffs or duties arising in connection with your use of the Site and shall fully comply with applicable federal, state, and local laws relating to your use of the Site and any revenue you receive hereunder.</li>
</ol>


<h3>Restrictions of Use</h3>
<p>You agree to use the Site only as provided herein. We have the right to confiscate (and not pay out on) any account whose conduct violates our Restrictions on Use.</p>

<p>Therefore you shall not:</p>
<ul>
<li>Access or attempt to access any other user’s account, or misrepresent or attempt to misrepresent your identity while using the Site, including misrepresentation as a Sequel Media International, LLC agent or representative, or misrepresentation stating or implying our endorsement of you or your product or activity.</li>
<li>Transmit to the Site any content, or conduct yourself in any manner, that could be construed as defamatory, libelous, obscene, bigoted, hateful, racially offensive, vulgar, harassing, inflammatory, pornographic, violent, profane, threatening, unfair, inaccurate, deceptive or unlawful, or that could constitute or encourage conduct that would be considered a criminal offense or give rise to civil liability, whether under statute, common law or equitable principles, or otherwise violate any law.</li>
<li>Publish posts that are excessively promotional. Brands are invited to post content on our platform, however posts must be of a general interest nature, and not promoting direct sales. As an example, an automobile manufacturer may post an article describing great places to take driving vacations, with a mention of their brand name in the body copy, but may not post an article promoting an upcoming sale; a small chiropractor may publish an article about ways to exercise that are beneficial for your back, with their name, number and other information in their profile, but may not post an article that strictly discusses their practice and why people should use their services. PuckerMob reserves the right to remove articles we feel violate these rules, or close accounts that post such articles at our discretion.</li>
<li>Post unsuitable account content such as posts or images that: are not your original material, merely contain images or less than 1,000 characters, are not written in English or lack an English translation, or contain referral or affiliate links to other websites. We do not pay on unsuitable content and posts containing unsuitable content will be removed in our sole discretion.</li>
<li>Abuse the Site’s likes/views/comment system by any means including but not limited to use of exchange groups, or utilizing code, tags, cookies, Traffic Exchange, bots, proxies, virtual private network or other forms of social or digital manipulation to generate non-authentic likes/views/comment on your posts.</li>
<li>Falsify or delete any author attributions, copyright notices or legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, or that is provided with Site materials or accessed through the Site.</li>
<li>Conduct or forward surveys, contests, pyramid schemes or chain letters.</li>
<li>Send any bulk commercial email, or send any unsolicited email to any party.</li>
<li>Harvest or otherwise collect information about others, including e-mail addresses.</li>
<li>Use the Site in any manner which could damage, disable, overburden, or impair the Site or interfere with any other party's use and enjoyment of the Site.</li>
<li>Use the Site in any manner that could create a risk to a person’s safety or health, creates a risk to public safety or health, compromises national security, or interferes with an investigation by law enforcement.</li>
<li>Obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Site.</li>
<li>Violate any code of conduct or other guidelines which may be applicable to any particular Site services.</li>
<li>Violate any applicable laws or regulations, including any intellectual property laws or regulations, or violate these Terms of Service.</li>
<li>Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another's computer or of the Site server.</li>
</ul>

<h3>INFORMATION DISCLOSURE</h3>
<p>Disclosure under Law</p>
<p>Sequel Media International, LLC reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, including personally identifiable information, or to edit, refuse to allow or to remove any information or materials, in whole or in part, in Sequel Media International, LLC’ sole discretion.</p>
<p>Providing Correct Personal Information</p>
<p>In the course of using the Site, you may be required to enter certain information, including without limitation personal information (collectively, “Information”). You represent and warrant that you will provide Sequel Media International, LLC with full, true and correct Information, and to update such Information on the Site promptly as reasonably necessary and as required by the Site.</p>

<h3>MATERIALS</h3>
<p>License in Materials</p>
<p>Sequel Media International, LLC does not claim ownership of any data, information (personal or otherwise) or other materials that you enter through the Site (collectively, "Materials"). There are two types of Materials: (a) Materials that are uploaded through the accounts of users of the password-protected portion of the Site for purposes specific to such user (collectively, “Account Materials”), and (b) Materials that are uploaded by users for purposes of general dissemination, such as postings to PuckerMob.com, or Feedback, defined below (collectively, “General Materials”). By transmitting, uploading, inputting, providing or submitting (collectively, “Submitting” or “Submit”) any Account Materials, you are granting Sequel Media International, LLC, its affiliated companies and sublicensees a non-exclusive, royalty-free, worldwide right to (i) post such materials for your access and use, (ii) provide your Account Materials to other users, (iii) use your Account Materials for marketing purposes and (iv) make those uses of Account Materials that are either identified at the time you provide such Account Materials or can reasonably be anticipated by you, all while your account with Sequel Media International, LLC remains open, and to archive such materials thereafter. By Submitting any General Materials, you are granting Sequel Media International, LLC, its affiliated companies and sublicensees a non-exclusive, royalty-free, perpetual, worldwide, irrevocable and fully sublicenseable license in and to such General Materials for use for any purpose, and confirming that such General Materials are non-confidential and non-proprietary. You hereby waive all rights to any claim against Sequel Media International, LLC Entities (defined below) and any Site users for any alleged or actual infringements of any proprietary rights, rights of privacy and publicity, moral rights, and rights of attribution in connection with Materials. In the event that you Submit to Sequel Media International, LLC any Account Materials for the purpose of making such materials generally accessible to other Site users, such as posting such materials on Sequel Media International, LLC’ blog, such materials will be deemed General Materials and you grant Sequel Media International, LLC a General Materials license in such materials.</p>


<p>Feedback</p>
<p>If you provide Sequel Media International, LLC with Materials such as comments, bug reports, feedback or modifications proposed by you to Sequel Media International, LLC, the Site, or the goods and/or services provided through the Site (collectively, “Feedback”), then in addition to the license granted in all Materials, Sequel Media International, LLC will have the right to use such Feedback at Sequel Media International, LLC’ discretion, including but not limited to incorporating such Feedback into the Site and the right to assign, license or otherwise use such Feedback. You hereby give Sequel Media International, LLC a perpetual, irrevocable, non-exclusive license under all rights necessary to incorporate such Feedback and use such Feedback for any purpose. No compensation will be paid with respect to the use of your Materials.</p>
<p>Your Responsibility for Materials and Sequel Media International, LLC’ Monitoring Rights</p>
<p>You will be responsible for your own Materials and the consequences of transmitting those Materials. Sequel Media International, LLC has no obligation to monitor you or any other user’s use of the Site. Sequel Media International, LLC reserves the right to review and monitor your use of the Site, including without limitation your use of any user ID and/or password in accessing the Site and any Materials Submitted to or revised on the Site, and to remove any Materials that Sequel Media International, LLC believes in its sole discretion violate these Terms of Service. Sequel Media International, LLC reserves the right to restrict or terminate your access to the Site, including, without limitation, your access to any or all of the services provided thereunder or your ability to use any Site user ID and/or password, at any time without notice if we believe you have violated these Terms of Service or are likely to violate these Terms of Service. Your sole remedy against Sequel Media International, LLC in the event of a dispute arising out of these Terms of Service, the Site or your use thereof, is to terminate these Terms of Service by ceasing your use of the Site. In the event of termination of these Terms of Service, Sequel Media International, LLC may delete and/or store, in its discretion, Materials and data associated with your use of the Site. Sequel Media International, LLC may also change, suspend, or discontinue any aspect of the publicly available portion of the Site at any time, including the availability of any Site feature, database, or content. With regard to the password-protected portion of the Site, Sequel Media International, LLC will provide you with fifteen (15) days notice prior to materially changing, suspending or discontinuing any aspect of this portion of the Site.</p>

<h3>USER REPRESENTATIONS AND WARRANTIES</h3>
<p>By using or accessing the Site or Submitting your Materials, you (1) represent and warrant that you own or otherwise control all of the rights to your Materials necessary to grant the licenses granted in these Terms of Service, including, without limitation, all the rights necessary for you to Submit the Materials, and have all right, power and authority to enter into these Terms of Service and to fully perform hereunder, (2) represent and warrant that your use of the Site, Site content and/or Materials does not and will not violate or infringe any third party right, including but not limited to any third party intellectual property right, right of publicity or privacy, right of trade secret or confidentiality, or contractual right, or violate these Terms of Service, the <a href="http://www.puckermob.com/privacy/">Privacy Policy</a>, the Compensation Policy, or any other agreement to which you are bound or any law, rule, regulation, order or judgment to which you are subject, (3) represent and warrant that you will comply with all applicable laws, contracts and/or agreements, at your sole expense and liability, in connection with your use of or access to the Site, (4) represent and warrant that you will only Submit and use Materials that may be used in accordance with the licenses you have granted herein and (5) agree that Sequel Media International, LLC shall not be liable to you or any third party for accepting or not accepting your Materials or for deleting or not deleting your Materials, in whole or in part.

<h3>DISCLAIMERS</h3>
<p>Forward Looking Statements</p>
<p>The Site may contain forward looking statements that are subject to risks and uncertainties that might cause actual results to differ from those foreseen. We wish to caution you that these statements are only predictions and those actual events or results may differ materially. Sequel Media International, LLC assumes no obligation, and does not intend to update these forward-looking statements.</p>

<p>External Links or References</p>
<p>The Site may contain links or references to other parties' sites, which links are provided as a convenience to you only. Please be aware that we cannot be and are not responsible for the privacy or other practices of any such outside sites (which sites are not part of the Site), and Sequel Media International, LLC expressly disclaims any and all liability related to such sites and sites relating thereto. Sequel Media International, LLC does not endorse, and is not responsible or liable for, directly or indirectly, any damage or loss caused or alleged to be caused by or in connection with any content, advertising, products or other information on or available from such linked sites or any link contained in a linked site. We encourage our users to consider this if they decide to visit such outside sites and to read the applicable <a href="http://www.puckermob.com/privacy/">Privacy Policies</a> and terms of use of each such sites.</p>

<p>DISCLAIMER OF REPRESENTATIONS AND WARRANTIES</p>
<p>YOU AGREE THAT YOUR USE OF THE SITE IS AT YOUR OWN RISK. EFFORTS BY SEQUEL MEDIA INTERNATIONAL, LLC TO MODIFY THE SITE SHALL NOT BE DEEMED A WAIVER OF THESE LIMITATIONS. THE SITE, INCLUDING ALL CONTENT, INFORMATION OR SERVICES PROVIDED THROUGH, OR IN CONJUNCTION WITH, THE SITE, IS PROVIDED "AS IS," AS A CONVENIENCE TO ALL USERS WITHOUT REPRESENTATION OR WARRANTY OF ANY KIND TO YOU OR ANY THIRD PARTY, INCLUDING, WITHOUT LIMITATION, ANY EXPRESS OR IMPLIED WARRANTIES (1) OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, (2) OF INFORMATIONAL CONTENT OR ACCURACY, (3) OF NON-INFRINGEMENT, (4) OF QUIET ENJOYMENT, (5) OF TITLE, (6) THAT THE SITE WILL OPERATE IN AN ERROR FREE, TIMELY, SECURE, OR UNINTERRUPTED MANNER, IS CURRENT AND UP TO DATE AND ACCURATELY DESCRIBES SEQUEL MEDIA INTERNATIONAL, LLC’ PRODUCTS AND SERVICES, OR IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, (7) THAT ANY DEFECTS OR ERRORS IN THE SITE WILL BE CORRECTED, OR (8) THAT THE SITE IS COMPATIBLE WITH ANY PARTICULAR HARDWARE OR SOFTWARE PLATFORM.</p>
<p>DISCLAIMER OF LIABILITY</p>
<p>IN NO EVENT SHALL SEQUEL MEDIA INTERNATIONAL, LLC AND ITS OFFICERS, DIRECTORS, AGENTS, EMPLOYEES, REPRESENTATIVES, INTERNAL OPERATING UNITS, AFFILIATES, SUBSIDIARIES, SUBLICENSEES, SUCCESSORS AND ASSIGNS, INDEPENDENT CONTRACTORS, AND RELATED PARTIES (COLLECTIVELY, WITH SEQUEL MEDIA INTERNATIONAL, LLC, THE “SEQUEL MEDIA INTERNATIONAL, LLC ENTITIES”) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOSS OF PROFITS, LOSS OF USE, LOSS OF DATA, INTERRUPTION OF BUSINESS, OR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE SITE OR WITH THE DELAY OR INABILITY TO USE SAME, OR FOR ANY BREACH OF SECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE INFORMATION THROUGH THE SITE, OR FOR ANY INFORMATION, PRODUCTS, AND SERVICES OBTAINED THROUGH OR VIEWED ON THE SITE, OR OTHERWISE ARISING OUT OF THE USE OF SAME, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY, REGULATION, COMMON LAW PRECEDENT OR OTHERWISE, EVEN IF SEQUEL MEDIA INTERNATIONAL, LLC HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES AND EVEN IF SUCH DAMAGES RESULT FROM SEQUEL MEDIA INTERNATIONAL, LLC’ NEGLIGENCE OR GROSS NEGLIGENCE. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, LIABILITY OF SEQUEL MEDIA INTERNATIONAL, LLC ENTITIES SHALL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW. ADDITIONAL DISCLAIMERS APPEAR WITHIN THE BODY OF THE SITE AND ARE INCORPORATED HEREIN BY REFERENCE. TO THE EXTENT ANY SUCH DISCLAIMERS PLACE GREATER RESTRICTIONS ON YOUR USE OF THE SITE OR THE MATERIAL CONTAINED THEREIN, SUCH GREATER RESTRICTIONS SHALL APPLY. THIS INDEMNIFICATION SHALL APPLY TO THIRD PARTY CLAIMS AS WELL AS CLAIMS BETWEEN THE PARTIES.</p>

<p>Indemnification</p>
<p>You will indemnify, defend (or settle) and hold harmless Sequel Media International, LLC Entities from all claims, actions, proceedings, losses, settlements, judgments, liabilities, suits, damages, disputes or demands, including without limitation any proceeding, investigation or claim by a self-regulatory organization, state or federal securities agency or commission, and including reasonable attorneys fees and all other costs, fees, and expenses (collectively, “Claims”) against any of Sequel Media International, LLC Entities to the fullest extent permitted by law arising out of or in connection with (1) your conduct, provision of content or use of the Site, or such actions by any third party through you, (2) your violation of the rights of another person or party, (3) any Materials provided or made available by you, and (4) any breach or violation by you of your obligations under these Terms of Service, including without limitation any breach of your representations and warranties herein. You will not settle any indemnified claim without the prior written consent of Sequel Media International, LLC, such consent not to be unreasonably withheld. In connection with any Claims that may give rise to your indemnification obligations as set forth above, Sequel Media International, LLC Entities shall have the exclusive right, at their option, to defend, compromise and/or settle the suit, action or proceeding, and you shall be bound by the determination of any suit, action or proceeding so defended or any compromise or settlement so effected. The remedies provided in this Section are not exclusive of and do not limit any other remedies that may be available to Sequel Media International, LLC Entities pursuant to this Section.</p>

<h3>YOUR ACCOUNT</h3>

<p>Payments</p>
<p>We redeem funds you generate from the Site to you in the form of a PayPal deposit. You are solely responsible and shall pay all local, state, federal, and international assessments, duties, taxes or other levy on funds you generate from the Site under all applicable laws. Users under the age of 13 are not allowed to visit or otherwise use the Site. We do not knowingly create Sequel Media International, LLC accounts for such persons and will confiscate any such unauthorized accounts upon notice of the age of the user.</p>
<p>Users under the age of 18 shall not register on Sequel Media International, LLC to accept payments without the written authorization of the user’s parent or legal guardian who shall submit supplemental information to the user’s account directing funds to be redeemed to the parent’s or guardian’s account. Unauthorized accounts shall be confiscated upon notice of the unauthorized account.</p>

<p>Security of Account and Password</p>
<p>In the event you establish an account and receive or establish a password for such account, you are responsible for maintaining the confidentiality of your account and password, and for restricting access to your computer. You accept full responsibility and liability for all activities that occur under your account or password. Sequel Media International, LLC reserves the right to refuse service, terminate accounts, or remove content in its sole discretion. You represent and warrant that the information you supply during any registration or update process will be accurate and complete and that you will not (1) impersonate or misrepresent your association with any person or entity, including without limitation registering under the name of another person, or seek to conceal or misrepresent the origin of any content or information provided by you, (2) choose a user name that Sequel Media International, LLC in its sole discretion deems inappropriate, or (3) choose a user name for the purposes of deceiving or misleading Sequel Media International, LLC as to your true identity. You agree not to impersonate any other person.</p>

<p>Notification of Unauthorized Use/Ceasing Access</p>
<p>You shall notify Sequel Media International, LLC immediately of any unauthorized use or threat of unauthorized use of your account or the Site or of any other breach or potential breach of security known to you with respect to your account or the Site, including without limitation any loss or compromise of any password, and will cooperate with Sequel Media International, LLC in every reasonable way to help Sequel Media International, LLC prevent the further unauthorized use, threat of unauthorized use, disclosure or threat of disclosure regarding the Site, your account and/or your password. You agree that immediately upon termination of your right to use the Site or any password-protected portion of the Site, or upon any earlier demand by Sequel Media International, LLC at any time, you will cease all access and/or use of the Site or such password protected portion of the Site, and will not attempt to access and/or use same.</p>

<h3>CONFIDENTIALITY</h3>
<p>You acknowledge that by use of portions of the Site, you may use and you may acquire Sequel Media International, LLC Confidential Information. As used herein, “Confidential Information” means all confidential and/or proprietary information and trade secrets of Sequel Media International, LLC, whether or not memorialized, and in any form or media, regarding Sequel Media International, LLC or Sequel Media International, LLC’ business, including without limitation those relating to Sequel Media International, LLC’ intellectual property, technology, research and development, systems, software, business plans, business operations, strategies, financial information, technical information, customers, customer lists, suppliers, operating policies and procedures, and any third-party information that Sequel Media International, LLC is required to keep confidential where such information is not generally accessible without a password. “Confidential Information” includes any account passwords. You shall not at any time, directly or indirectly, for any purpose, use, copy or disclose to any other person or entity any Confidential Information, or permit others to do so, other than for the purposes expressly allowed hereunder. Sequel Media International, LLC may seek and obtain injunctive relief against the release or threatened release of Confidential Information, in addition to any other available legal remedies. You shall notify Sequel Media International, LLC immediately if you learn of any unauthorized possession or use of the Confidential Information and will promptly furnish all details of such possession or use to Sequel Media International, LLC.</p>

<h3>COPYRIGHT AND OTHER INTELLECTUAL PROPERTY</h3>
<p>Site Ownership</p>
<p>The Site and all content, organization, graphics, design, compilation, magnetic translation, digital conversion, and other matters related to the Site (collectively, “Content”) are protected under applicable copyrights, trademarks, and other proprietary (including but not limited to intellectual property) rights pursuant to international conventions and U.S. and other laws. The Site and all Content is the property of Sequel Media International, LLC and/or third party licensors, and all right, title and interest in and to the Site and Content will remain with Sequel Media International, LLC or such third party licensors. Other product and company names mentioned herein may be the trademarks of their respective owners. You do not acquire ownership rights to the Site or any Content other than any rights in the Materials that you may have. You will abide by any and all additional copyright notices, information, or restrictions contained in any Content. You will not modify, adapt, translate, reverse engineer, decompile, or disassemble the Site or any Site content. You may only use the Site and the Content as expressly permitted herein, and any other use is prohibited. Any copying, republication, or redistribution of the Site or Site content, including by caching, framing, or similar means, is expressly prohibited without the prior written consent of Sequel Media International, LLC and/or the respective intellectual property rights holder identified in the subject content, which consent to be granted or withheld at the sole discretion of the rights holder.</p>
<p>Copyright Infringement Claims</p>
<p>Sequel Media International, LLC respects the intellectual property rights of others and expects our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide Sequel Media International, LLC’ Designated Copyright Agent, identified below, with all information required by the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act (“DMCA”), 17 U.S.C. § 512, summarized as follows: (1) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (2) identification of the copyright work claimed to have been infringed, or, if multiple copyrighted works at a single online Site are covered by a single notification, a representative list of such works at that Site; (3) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; (4) information reasonably sufficient to permit us to contact the complaining party; (5) a statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; (6) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; and (7) any other materials or information as may be required under the DMCA as amended from time to time or by the U.S. Copyright Office.</p>
<p>Copyright Agent</p>
<p>Pursuant to the DMCA, written notification of claimed copyright infringement must be submitted to Sequel Media International, LLC Designated Copyright Agent using the following contact information:</p>


<h3>SEQUEL MEDIA INTERNATIONAL, LLC DESIGNATED COPYRIGHT AGENT CONTACT INFO:</h3>
<p>Email: info@sequelmediainternational.com</p>

<p>ALL INQUIRIES NOT RELEVANT TO THE ABOVE PROCEDURE WILL RECEIVE NO RESPONSE.</p>

<h3>DISPUTE RESOLUTION</h3>
<p>MANDATORY BINDING ARBITRATION</p>
<p>YOU AND SEQUEL MEDIA INTERNATIONAL, LLC EACH AGREE TO SUBMIT TO BINDING ARBITRATION IN THE EVENT OF A DISPUTE, CONTROVERSY OR CLAIM (EACH, A “DISPUTE”) ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF SERVICE OR THE BREACH, TERMINATION, ENFORCEMENT, INTERPRETATION OR VALIDITY THEREOF (INCLUDING THE DETERMINATION OF THE SCOPE OR APPLICABILITY OF THESE TERMS OF SERVICE TO ARBITRATE), YOUR OR SEQUEL MEDIA INTERNATIONAL, LLC’ RIGHTS AND OBLIGATIONS UNDER THESE TERMS OF SERVICE, THE SITE, THE USE OF THE SITE, AND/OR THE INFORMATION, SERVICES AND/OR PRODUCTS THAT MAY BE PROVIDED BY OR THROUGH OR IN CONNECTION WITH THE SITE. THE ARBITRATION WILL BE HELD IN NEW YORK, NY BEFORE ONE ARBITRATOR ON AN INDIVIDUAL BASIS AND NOT AS A CLASS ACTION. YOU EXPRESSLY WAIVE ANY RIGHT YOU MAY HAVE TO ARBITRATE A DISPUTE AS A CLASS ACTION. YOU ALSO EXPRESSLY WAIVE YOUR RIGHT TO A JURY TRIAL. THE ARBITRATION WILL BE ADMINISTERED BY JAMS (HTTP://WWW.JAMSADR.COM). YOU MAY OBTAIN A COPY OF THE RULES OF JAMS BY CONTACTING THE ORGANIZATION. YOU AND SEQUEL MEDIA INTERNATIONAL, LLC SHALL AGREE ON ONE ARBITRATOR TO CONDUCT THE ARBITRATION. IN THE EVENT THE PARTIES CANNOT AGREE ON AN ARBITRATOR, THE ARBITRATOR WILL BE SELECTED IN ACCORDANCE WITH THE JAMS RULES. EACH PARTY SHALL BE RESPONSIBLE FOR ITS OWN ATTORNEY, EXPERT AND OTHER FEES, UNLESS SUCH FEES ARE AWARDED BY THE ARBITRATOR TO THE PREVAILING PARTY. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS SECTION, TO THE EXTENT YOU HAVE IN ANY MANNER VIOLATED OR THREATENED TO VIOLATE SEQUEL MEDIA INTERNATIONAL, LLC’ INTELLECTUAL PROPERTY RIGHTS, SEQUEL MEDIA INTERNATIONAL, LLC MAY SEEK (AND YOU WILL NOT CONTEST) INJUNCTIVE OR OTHER APPROPRIATE RELIEF IN ANY STATE OR FEDERAL COURT IN SAN FRANCISCO, CALIFORNIA AND YOU CONSENT TO THE EXCLUSIVE JURISDICTION AND VENUE OF SUCH COURTS.</p>

<p>ARBITRATION FINAL AND BINDING</p>
<p>THE ARBITRATOR'S AWARD IS FINAL AND BINDING ON ALL PARTIES. THE FEDERAL ARBITRATION ACT, AND NOT ANY STATE LAW CONCERNING ARBITRATION, GOVERNS ALL ARBITRATION UNDER THIS CLAUSE. ANY COURT HAVING JURISDICTION MAY ENTER JUDGMENT ON THE ARBITRATOR'S AWARD. IF ANY PART OF THIS CLAUSE, OTHER THAN WAIVERS OF CLASS ACTION RIGHTS, IS DEEMED OR FOUND TO BE UNENFORCEABLE FOR ANY REASON, THE REMAINDER SHALL REMAIN ENFORCEABLE. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IF THE WAIVER OF CLASS ACTION RIGHTS CONTAINED HEREIN IS NOT ENFORCEABLE AS TO ANY PERSON OR PERSONS, SUCH NON-ENFORCEABILITY SHALL APPLY TO SUCH PERSON OR PERSONS ONLY, AND ALL OTHER PERSONS SHALL CONTINUE TO BE GOVERNED BY THE ARBITRATION CLAUSE.</p>

<p>GIVING UP RIGHT OF CLASS ACTION</p>
<p>THESE TERMS OF SERVICE PROVIDES THAT ALL DISPUTES WILL BE RESOLVED BY BINDING ARBITRATION AND NOT IN COURT OR BY JURY TRIAL. IF A DISPUTE IS ARBITRATED, YOU GIVE UP YOUR RIGHT TO PARTICIPATE AS A CLASS REPRESENTATIVE OR CLASS MEMBER ON ANY CLASS ACTION CLAIM YOU MAY HAVE AGAINST SEQUEL MEDIA INTERNATIONAL, LLC ENTITIES INCLUDING ANY RIGHT TO CLASS ARBITRATION OR ANY CONSOLIDATION OF INDIVIDUAL ARBITRATIONS. WITHOUT LIMITATION, THIS INCLUDES GIVING UP YOUR RIGHTS TO BRING OR PARTICIPATE IN A CLASS ACTION AS SET FORTH IN ANY STATE STATUTE.</p>

<p>Choice of Law; Jurisdiction and Venue; Waiver of Jury Trial</p>
<p>To the maximum extent permitted by law, these Terms of Service are governed by the laws of the United States of America and the State of New York, excluding any law or conflicts of law principle that would apply the law of another jurisdiction. To the extent a Dispute is not governed by the Arbitration Clause, you hereby consent to the exclusive jurisdiction and venue of courts in New York, NY in all disputes arising out of or relating to the use of the Site or under these Terms of Service; provided, however, that in the event Sequel Media International, LLC is sued or joined by a third party in any other court or in any other forum in respect of any matter which may give rise to a claim by Sequel Media International, LLC hereunder, you consent to the jurisdiction of such court or forum over any claim which may be asserted by Sequel Media International, LLC therein. You irrevocably consent to the exercise of personal jurisdiction by such courts in any such action. In addition, and notwithstanding the foregoing, you irrevocably waive, to the fullest extent permitted by law, any objection that you may now or hereafter have to the laying of the venue of any such suit, action or proceeding brought in any such court and any claim that any such suit, action or proceeding brought in any such court has been brought in an inconvenient forum. Final judgment in any such suit, action or proceeding brought in any such court shall be conclusive and binding upon you and may be enforced in any court in which you are subject to a jurisdiction by a suit upon such judgment. Use of the Site is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms of Service, including without limitation this paragraph. To the extent a claim is not governed by the Arbitration Clause, Sequel Media International, LLC and you each hereby waive the right to a trial by jury in any court and in any suit, action or proceeding, whether in tort, contract, or otherwise, in which any such party is a party, as to any claim arising out of or in connection with these Terms of Service, your or Sequel Media International, LLC’ rights and obligations under these Terms of Service, the Site, use of the Site, and/or the services and/or products that may be provided by or through or in connection with the Site.</p>

<h3>MISCELLANEOUS</h3>
<p>Viewing, Accessing and Use Outside the United States</p>
<p>If and when any products or services referenced on the Site become available, they will become available in the United States and may not become available elsewhere. Sequel Media International, LLC makes no claims that the Site or any products or services referenced therein may be lawfully viewed, accessed or used outside the United States. Access or use of the Site or any products or services referenced therein may not be legal by certain persons or in certain countries. If you access or use the Site from outside of the United States, you do so at your own risk and you are responsible for compliance with the laws of your jurisdiction.
<p>No Joint Venture</p>
<p>You agree that no joint venture, partnership, employment or agency relationship exists between you and Sequel Media International, LLC as a result of these Terms of Service or your use of the Site.</p>

<p>Headings</p>
<p>Section headings and other captions in these Terms of Service are used solely for the convenience of the parties, have no legal or contractual significance, and shall not be used in interpreting, construing or enforcing any of the provisions of these Terms of Service.</p>

<p>Survival</p>
<p>The provisions of the following sections shall survive any termination or expiration of these Terms of Service: Disclosure Under Law, Materials, User Representations and Warranties, Disclaimers, Indemnification, Confidentiality, Copyright and Other Intellectual Property, Dispute Resolution (Arbitration Clause), Choice of Law; Jurisdiction and Venue; Waiver of Jury Trial, and Miscellaneous.</p>

<p>No Waiver</p>
<p>The failure of Sequel Media International, LLC to enforce any provision of these Terms of Service will not be construed as a waiver or limitation of Sequel Media International, LLC’ right to subsequently enforce and compel strict compliance with that provision or any other provision of these Terms of Service.</p>

<p>Assignment</p>
<p>No assignment, delegation or other conveyance of these Terms of Service may be made by you (by operation of law or otherwise) without the prior written consent of Sequel Media International, LLC, to be given in its sole discretion. Sequel Media International, LLC may assign its rights and obligations hereunder to any other party.</p>

<p>Statute of Limitations</p>
<p>Any cause of action you may have with respect to your use of the Site must be commenced within one year after the claim or cause of action arises; thereafter, any such claim will be forever barred, without regard to any contrary legislation.</p>

<p>Agreement Binding</p>
<p>In the event that any provision of these Terms of Service is deemed to be unenforceable, said provision will be interpreted to reflect the original intent of the parties in accordance with applicable law, and the remainder of these Terms of Service will continue in full force and effect.</p>

<p>Notices</p>
<p>Notices to Sequel Media International, LLC under these Terms of Service shall be sufficient only if in writing and transmitted via personal delivery, delivered by a major commercial rapid delivery courier service, or mailed, postage or charges prepaid, by certified or registered mail, return receipt requested, to Sequel Media International, LLC, with such notices being effective as of the date of actual, confirmed receipt by Sequel Media International, LLC. Notices to you are deemed effective if sent to the email, mail address or other contact information provided by you, and are deemed effective upon the earlier of being confirmed received or one day after having been sent.</p>

<p>Entire Agreement; Language of Agreement</p>
<p>These Terms of Service contain the entire agreement between you and Sequel Media International, LLC with respect to the Site. It supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Sequel Media International, LLC with respect to the Site. Any rights not expressly granted herein are reserved. A printed version of these Terms of Service and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms of Service to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish of the parties that these Terms of Service and all related documents be drawn up in English.</p>

<hr class="hr-hidden">
</section>

</section>
<?php 
	if ( !$detect->isMobile() ) { 
		include_once($config['include_path'].'rightsidebar.php');
	 }
	 ?>
</main>
<?php include_once($config['include_path'].'footer.php'); ?>
<?php include_once($config['include_path'].'bottomscripts.php'); ?>
</body>
</html>
